config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :cryptos, only: [:index, :show] do
    resources :holdings, only: [:create, :update]
    resources :watchlists, only: [:create]
  end

  resources :holdings, only: [:index, :update]
  resources :watchlists, only: [:index, :destroy]

  get 'my_dashboard', to: 'holdings#index'
  get 'articles', to: 'pages#articles'
  get 'jargonbuster', to: 'pages#jargonbuster', as: 'jargon_buster'
  get :advance_date, to: 'holdings#advance_date', as: 'change_simulation'
  get :advance_date_week, to: 'holdings#advance_date_week', as: 'change_simulation_week'
  get :reset_holdings, to: 'holdings#reset_holdings', as: 'reset_holdings'
  # get :advance_date_index, to: 'holdings#advance_date_index', as: 'change_simulation_index'
  # get :advance_date_week_index, to: 'holdings#advance_date_week_index', as: 'change_simulation_week_index'
  # get :advance_date_show, to: 'holdings#advance_date_show', as: 'change_simulation_show'
  # get :advance_date_week_show, to: 'holdings#advance_date_week_show', as: 'change_simulation_week_show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <ul id="footer-list">
      <a href=""><li><i class="fab fa-github"></i></li></a>
      <a href=""><li><i class="fab fa-facebook"></i></li></a>
      <a href=""><li><i class="fab fa-twitter"></i></li></a>
      <a href=""><li><i class="fab fa-instagram"></i></li></a>
      <a href=""><li><i class="fab fa-linkedin"></i></li></a>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="menu">
  <div class="options">
    <% if user_signed_in? %>
      <ul>
        <li>
          <%= link_to 'Home', root_path%>
        </li>
        <li>
          <%= link_to 'Dashboard', my_dashboard_path%>
        </li>
        <li>
          <%= link_to 'Watchlist', watchlists_path%>
        </li>
        <li>
          <%= link_to 'Browse Cryptos', cryptos_path%>
        </li>
        <li class="dropdown">
            <button class="dropbtn">Learn More</button>
            <div class="dropdown-content">
              <%= link_to 'Jargon Buster', jargon_buster_path%>
              <%= link_to 'Articles', articles_path%>
            </div>
        </li>
        <li class ="nav-item dropdown">
        <div class="dropdown">
          <button class="btn btn-basic dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">

            <img class="avatar-bordered nav-avatar" alt="avatar" src="https://avatars.githubusercontent.com/u/97609680?v=4" />
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>

            <li><%= link_to 'Reset Holdings',reset_holdings_path, data: { confirm: "Are you sure?" }, class: "dropdown-item" %></li>
          </ul>
        </div>
        </li>
      </ul>
      <ul class="simulation-navbar">
        <li style="margin-right:20px">
          <h6>Simulation Date: <%= current_user.simulation_date.strftime('%d/%m/%Y') %></h6>
        </li>
        <li>
          <%= link_to '+1 Day', change_simulation_path(current_user), style:'color:#FF840A', id:'date-sim-btn' %>
        </li>
        <li>
          <h6>|</h6>
        </li>
        <li>
          <%= link_to '+7 Days', change_simulation_week_path(current_user), style:'color:#FF840A', id:'date-sim-btn' %>
        </li>
        <li style="margin-left:20px">
          <h6 style="color:#FF840A">Balance: $<%= number_with_precision(current_user.balance, :precision => 2, :delimiter => ',') %></h6>
        </li>
      </ul>
    <% else %>
    <% end %>
  </div>
  <%# Script to make it scroll back down to the part of the page you was on when it was clicked. %>
  <%# the if statement says for it to only run on the cryptos controller index page %>
  <% if params[:controller] == 'cryptos' && params[:action] == 'index' %>
    <script>
        document.addEventListener("DOMContentLoaded", function (event) {
            var scrollpos = sessionStorage.getItem('scrollpos');
            if (scrollpos) {
                window.scrollTo(0, scrollpos);
                sessionStorage.removeItem('scrollpos');
            }
        });

        window.addEventListener("beforeunload", function (e) {
            sessionStorage.setItem('scrollpos', window.scrollY);
        });
    </script>
  <% end %>
</nav>